### ISSUE TITLE
resin.io host dnsmasq port conflict

### ISSUE THREAD

**Issue by MartyTremblay** [N2ITN/pihole3#1]
Just forked your project, thanks!

Wondering how you're able to circumvent the port 53 conflict issue? This is the error I'm getting:
dnsmasq: failed to create listening socket for port 53: Address already inuse

Tried setting env DNSMASQ_LISTENING to eth0 but didn't worked

**Comment by N2ITN** [comment]
@MartyTremblay  I was not able to find a satisfactory way of port forwarding (not to say there isn't one!)
See this repo for v2 of this project which is much more comprehensive: https://github.com/N2ITN/pi-zero-dns-filter

It uses Hyperiot OS instead of ResinIO to deploy a PiHole docker image from DockerHub. 
Features: 

- Wifi hotspot autoconfig, where the Raspberry Pi broadcasts hosts its own hotspot that hosts a web page that walks the user through the configuration.
- Automation: cron jobs to launch and update automatically and failovers to re-enable the hotspot if a network change happens. 
- When it's working right no ssh is needed. It should just work as a consumer product.

It works on a Raspberry Pi Zero (and definitely on Pi3). The downside is no remote management or updates, though it could be configured to git pull periodically. 

It's a year old so it may be of date- PRs are appreciated if you end up working on it!
Z

**Comment by MartyTremblay** [comment]
Thanks for the info @N2ITN , I'll explore v2 and see whether I can help. Cheers!
